# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://staaarrkk.github.io'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://i.pinimg.com/736x/4e/ac/36/4eac365f9bb78cac2fffda31c15f2cd5.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: The dumb homepage
  url: /
- title: What im currently listening to!
  url: /music/
- title: Posts n' shit
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: random shit or something
    output: true
    description: ""
    feature_text: |
      These are my thoughts
    feature_image: "https://dotandline.net/wp-content/uploads/2018/04/1_Qy1g-Ybpv5LSHjp5ZnK53w-1024x576.jpeg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
